name: sheet - web preview PR
on:
  pull_request:
    paths:
      - ".github/workflows/sheet-deploy-web-pull-request.yaml"
      - "sheet/**"
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    defaults:
      run:
        working-directory: sheet/example
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v3

      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: ğŸ“¦ Install Dependencies
        run: |
          flutter pub global activate very_good_cli
          very_good --analytics false
          very_good packages get --recursive

      - name: ğŸ›  Build web
        run: flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true

      - name: ğŸš€ Deploy to firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHEET_PREVIEW }}'
          projectId: sheet-preview
          entryPoint: sheet/example
